/** True when Supabase env is not configured — enables local UI tour with mock data. */
export function isUiPreviewMode(): boolean {
  const url = (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim();
  const key = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined)?.trim();
  if (import.meta.env.VITE_UI_PREVIEW === "true") return true;
  return !url || !key || url.includes("YOUR_");
}

export const PREVIEW_USER = {
  id: "preview-cge-user",
  name: "Aiden Hudson",
  email: "aiden@cge.preview",
  role: "admin" as const,
  roles: ["admin", "cge"] as ("admin" | "supervisor" | "cge" | "salesperson")[],
  initials: "AH",
  salesperson_name: "Aiden Hudson",
  hasDbRole: true,
};

export const PREVIEW_QUEUE_ROWS = [
  {
    id: "task-1",
    customer_id: "cust-1",
    salesperson_user_id: "sp-1",
    assigned_cge_user_id: "preview-cge-user",
    segment: "vip_inactive",
    status: "open",
    priority: 10,
    recency_days: 118,
    rfm_group: "Can Not Lose Them",
    last_outreach_at: null,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    customer_name: "Emma Johansson",
    customer_email: "emma@nordicsoft.example",
    customer_phone: "+447700900123",
    sp_assigned: "Rob Lister",
    total_orders: 14,
    total_revenue: 4820,
    customer_rfm_group: "Can Not Lose Them",
    customer_recency_days: 118,
  },
  {
    id: "task-2",
    customer_id: "cust-2",
    salesperson_user_id: "sp-1",
    assigned_cge_user_id: "preview-cge-user",
    segment: "one_time_lapsed",
    status: "open",
    priority: 20,
    recency_days: 96,
    rfm_group: "Need Attention",
    last_outreach_at: null,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    customer_name: "Ethan Wilson",
    customer_email: "ethan@travelventures.example",
    customer_phone: "+447700900456",
    sp_assigned: "Rob Lister",
    total_orders: 1,
    total_revenue: 189,
    customer_rfm_group: "Need Attention",
    customer_recency_days: 96,
  },
  {
    id: "task-3",
    customer_id: "cust-3",
    salesperson_user_id: "sp-2",
    assigned_cge_user_id: "preview-cge-user",
    segment: "lapsed_repeat",
    status: "in_progress",
    priority: 30,
    recency_days: 142,
    rfm_group: "Hibernating",
    last_outreach_at: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    customer_name: "Lily Walker",
    customer_email: "lily.walker@example.com",
    customer_phone: "+447700900789",
    sp_assigned: "Sam Patel",
    total_orders: 5,
    total_revenue: 910,
    customer_rfm_group: "Hibernating",
    customer_recency_days: 142,
  },
  {
    id: "task-4",
    customer_id: "cust-4",
    salesperson_user_id: "sp-2",
    assigned_cge_user_id: "preview-cge-user",
    segment: "never_purchased",
    status: "open",
    priority: 40,
    recency_days: null,
    rfm_group: "Lost",
    last_outreach_at: null,
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    customer_name: "William Lee",
    customer_email: "william.lee@example.com",
    customer_phone: null,
    sp_assigned: "Sam Patel",
    total_orders: 0,
    total_revenue: 0,
    customer_rfm_group: "Lost",
    customer_recency_days: null,
  },
  {
    id: "task-5",
    customer_id: "cust-5",
    salesperson_user_id: "sp-1",
    assigned_cge_user_id: "preview-cge-user",
    segment: "one_time_lapsed",
    status: "open",
    priority: 20,
    recency_days: 105,
    rfm_group: "About To Sleep",
    last_outreach_at: null,
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    customer_name: "Olivia Davis",
    customer_email: "olivia@example.com",
    customer_phone: "+447700900221",
    sp_assigned: "Rob Lister",
    total_orders: 1,
    total_revenue: 64,
    customer_rfm_group: "About To Sleep",
    customer_recency_days: 105,
  },
];

export const PREVIEW_KPIS = {
  open_tasks: 5,
  vip_inactive: 1,
  one_time_lapsed: 2,
  lapsed_repeat: 1,
  never_purchased: 1,
  recovered_orders: 3,
  outreach_count: 12,
};
